#!/usr/bin/env bash
# Workspace config for {{WORKSPACE_NAME}}.
# Sourced by .clawdbot/scripts/config.sh when B0B_WORKSPACE={{WORKSPACE_NAME}}.
# Generated by init-workspace.sh — edit by hand if you need to change values.

WORKSPACE_REPO="{{WORKSPACE_REPO}}"
BOT_USER="{{BOT_USER}}"
WORKTREE_BASE="{{WORKTREE_BASE}}"
SLACK_PROJECT_CHANNEL="{{SLACK_PROJECT_CHANNEL}}"
SLACK_ALERTS_CHANNEL="{{SLACK_ALERTS_CHANNEL}}"
SLACK_REVIEW_USER="{{SLACK_REVIEW_USER}}"
STATE_DIR="${HOME}/.openclaw/{{WORKSPACE_NAME}}/pipeline"
